apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: Run CDRO procedure
inputs:
  url:
    description: 'CDRO URL'
    required: false
    default: 'https://sda.preview.cb-demos.io'
  username:
    description: 'CDRO Username'
    required: true
  user-token:
    description: 'CDRO User token'
    required: true
  projectName:
    required: true
  procedureName:  
    required: true
  actualParameters:
    required: false
outputs: 
  jobId:
    value: "${{ steps.evalDSL.outputs.response }}"
runs:
  using: composite
  steps:
    - name: Checkout
          uses: cloudbees-io/checkout@v1

    - name: evalDSL
      uses: zvercodebender/cdrodsl-action/dslEval@v0.1
      with:
        url: "${{ vars.CB_FLOW }}"
        username: ${{secrets.CB_USER}}
        user-token: ${{secrets.CB_PASSWD}}
        file: "runProcedure.dsl"
        # "${{ inputs.projectName}}" "${{ inputs.procedureName}}" "${{ inputs.actualParameters}}"
